# Default values for thumbnail-api-server
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: false
  annotations: { }
  name: ""
image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""
imagePullSecrets: { }
env: { }
secretAnnotations: { }
podLabels: { }
podAnnotations: { }
podSecurityContext:
  fsGroup: 1000
  runAsUser: 1000
secretLabels: { }
volumes: { }
volumeMounts: { }
configs: { }
secrets: { }

app:
  server:
    service: { }
    replicaCount: 1
    autoscaling:
      enabled: false
    command: [ ]
    execArgs: [ ]
    resources: { }
    initContainers: [ ]
    podAnnotations: { }
    podLabels: { }
    podSecurityContext: { }
    livenessProbe: { }
    readinessProbe: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }
    ingress:
      enabled: false
      className: ""
      annotations: { }
      hosts: [ ]
      tls: [ ]

  worker:
    replicaCount: 1
    autoscaling:
      enabled: false
    command: [ ]
    execArgs: [ ]
    resources: { }
    initContainers: [ ]
    podAnnotations: { }
    podLabels: { }
    podSecurityContext: { }
    livenessProbe: { }
    readinessProbe: { }
    nodeSelector: { }
    tolerations: [ ]
    affinity: { }

# For dev environment, provision MinIO, Redis and PostgreSQL if set enabled to true
minio:
  enable: false
  rootUser: "minioadmin"
  rootPassword: "minioadmin"
  storage: "10Gi"
  defaultBucket: ""

redis:
  enable: false

postgresql:
  enable: false
  user: "postgres"
  password: "postgres"
  database: "thumbnail_db"
  storage: "10Gi"
